// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAswqqaq91XawkEbxfuDn9dlpX20roXFis',
    appId: '1:28216991755:web:742a3278f4dc4fea50e70e',
    messagingSenderId: '28216991755',
    projectId: 'ejegdsc',
    authDomain: 'ejegdsc.firebaseapp.com',
    storageBucket: 'ejegdsc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsgFtC8H8B467k43n4lcb6bCD9AfCj3jE',
    appId: '1:28216991755:android:6b269ca4755f6de650e70e',
    messagingSenderId: '28216991755',
    projectId: 'ejegdsc',
    storageBucket: 'ejegdsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rB7YVROHcySBPr7uNXp5-12Jg4Ccb2M',
    appId: '1:28216991755:ios:68915a04ccecdb2250e70e',
    messagingSenderId: '28216991755',
    projectId: 'ejegdsc',
    storageBucket: 'ejegdsc.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0rB7YVROHcySBPr7uNXp5-12Jg4Ccb2M',
    appId: '1:28216991755:ios:68915a04ccecdb2250e70e',
    messagingSenderId: '28216991755',
    projectId: 'ejegdsc',
    storageBucket: 'ejegdsc.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
